/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mascotapp.core;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public boolean anotherLibraryMethod() {
        return false;
    }
}
